### ISSUE TITLE
Splitting images up

### ISSUE THREAD

**Issue by CubePresser** [TheEnderPrime/OSUGameDevClubTeam#5]
- [x] Gets some image as input (png, jgp, whatever)
- [x] Divide the image into rows and columns
    - [x] Array representation of image segments (Probably just s,t ranges on the texture)
    - [x] Unity friendly data
- [x] Figure out ways to keep track of image states and correct positions to be stored along with image segments
- [x] Returns array of image segments

**Comment by TheEnderPrime** [comment]
Downloaded Image
Duplicated Image to maintain original copy after splitting
Changed Sprite Mode on Image to Multiple
Used Sprite Editor to SLICE by row count of 5x5
